/**
 * The payoff of the whole app: compare the tree you started with against the
 * tree you dragged into shape, and emit something you can actually run.
 *
 * Nodes are paired by `id`, not by path — that is what makes a drag read as a
 * `git mv` (which preserves history) rather than a delete plus an add.
 */

import type { FileNode } from '../store/treeOps';

export interface RepoChange {
  id: string;
  type: 'move' | 'add' | 'delete';
  /** Current path, or the path it used to have for a delete. */
  path: string;
  oldPath?: string;
  nodeType: 'file' | 'folder';
  name: string;
  /** True when an ancestor carries the same change, making this one redundant. */
  isNestedUnderChangedParent?: boolean;
}

export interface RepoDiff {
  changes: RepoChange[];
  /** Changes with redundant descendants removed — what the script acts on. */
  topLevelChanges: RepoChange[];
  totalCount: number;
}

export const EMPTY_DIFF: RepoDiff = { changes: [], topLevelChanges: [], totalCount: 0 };

interface FlatNode {
  id: string;
  path: string;
  name: string;
  type: 'file' | 'folder';
}

function flatten(nodes: readonly FileNode[]): Map<string, FlatNode> {
  const map = new Map<string, FlatNode>();
  const walk = (list: readonly FileNode[]) => {
    for (const node of list) {
      map.set(node.id, { id: node.id, path: node.path, name: node.name, type: node.type });
      if (node.children) walk(node.children);
    }
  };
  walk(nodes);
  return map;
}

export function computeRepoDiff(
  baseline: readonly FileNode[] | null,
  current: readonly FileNode[],
): RepoDiff {
  if (!baseline) return EMPTY_DIFF;

  const before = flatten(baseline);
  const after = flatten(current);
  const changes: RepoChange[] = [];

  for (const [id, node] of after) {
    const original = before.get(id);
    if (!original) {
      changes.push({ id, type: 'add', path: node.path, nodeType: node.type, name: node.name });
    } else if (original.path !== node.path) {
      changes.push({
        id,
        type: 'move',
        path: node.path,
        oldPath: original.path,
        nodeType: node.type,
        name: node.name,
      });
    }
  }

  for (const [id, node] of before) {
    if (!after.has(id)) {
      changes.push({ id, type: 'delete', path: node.path, nodeType: node.type, name: node.name });
    }
  }

  const movedFolders = changes.filter((c) => c.type === 'move' && c.nodeType === 'folder');
  const deletedFolders = changes.filter((c) => c.type === 'delete' && c.nodeType === 'folder');
  const addedFolders = changes.filter((c) => c.type === 'add' && c.nodeType === 'folder');

  for (const change of changes) {
    if (change.type === 'move' && change.oldPath) {
      // A move is redundant only if a moved ancestor carries it on *both* sides.
      change.isNestedUnderChangedParent = movedFolders.some(
        (folder) =>
          folder.id !== change.id &&
          change.oldPath!.startsWith(folder.oldPath! + '/') &&
          change.path.startsWith(folder.path + '/'),
      );
    } else if (change.type === 'delete') {
      change.isNestedUnderChangedParent = deletedFolders.some(
        (folder) => folder.id !== change.id && change.path.startsWith(folder.path + '/'),
      );
    } else {
      change.isNestedUnderChangedParent = addedFolders.some(
        (folder) => folder.id !== change.id && change.path.startsWith(folder.path + '/'),
      );
    }
  }

  const topLevelChanges = changes.filter((c) => !c.isNestedUnderChangedParent);

  return { changes, topLevelChanges, totalCount: topLevelChanges.length };
}

// ---------------------------------------------------------------------------
// Exporters
// ---------------------------------------------------------------------------

const strip = (p: string) => p.replace(/^\/+/, '');

const dirOf = (p: string) => {
  const parts = strip(p).split('/');
  parts.pop();
  return parts.join('/');
};

/** Single-quoted for the shell; the only escape needed is the quote itself. */
const shellQuote = (value: string) => `'${value.replace(/'/g, `'\\''`)}'`;

/** Heredoc bodies above this size are skipped, to keep the script pasteable. */
const MAX_INLINE_CONTENT = 4000;

export interface ShellScriptOptions {
  /** Content for added files, by path. Files without content are `touch`ed. */
  contents?: ReadonlyMap<string, string>;
}

export function generateShellScript(
  diff: RepoDiff,
  options: ShellScriptOptions = {},
): string {
  const { topLevelChanges } = diff;
  const contents = options.contents;

  const lines: string[] = [
    '#!/usr/bin/env bash',
    '# Generated by Visual Repository Planner.',
    '# Run from the root of the repository you opened.',
    'set -euo pipefail',
    '',
    'git rev-parse --show-toplevel >/dev/null 2>&1 || {',
    '  echo "Not inside a git repository — run this from your repo root." >&2',
    '  exit 1',
    '}',
    '',
  ];

  if (topLevelChanges.length === 0) {
    lines.push('echo "No changes to apply."');
    return lines.join('\n');
  }

  const moves = topLevelChanges.filter((c) => c.type === 'move');
  const adds = topLevelChanges.filter((c) => c.type === 'add');
  const deletes = topLevelChanges.filter((c) => c.type === 'delete');

  const dirs = new Set<string>();
  for (const change of [...moves, ...adds]) {
    const dir =
      change.type === 'add' && change.nodeType === 'folder'
        ? strip(change.path)
        : dirOf(change.path);
    if (dir) dirs.add(dir);
  }

  if (dirs.size > 0) {
    lines.push('# 1. Ensure target directories exist');
    for (const dir of Array.from(dirs).sort()) {
      lines.push(`mkdir -p ${shellQuote(dir)}`);
    }
    lines.push('');
  }

  if (moves.length > 0) {
    lines.push('# 2. Relocate tracked paths (preserves history)');
    // Deepest source first, so moving a child out of a folder that is itself
    // moving still resolves against a path that still exists.
    const ordered = [...moves].sort(
      (a, b) => strip(b.oldPath!).split('/').length - strip(a.oldPath!).split('/').length,
    );
    for (const move of ordered) {
      lines.push(`git mv ${shellQuote(strip(move.oldPath!))} ${shellQuote(strip(move.path))}`);
    }
    lines.push('');
  }

  const addedFiles = adds.filter((c) => c.nodeType === 'file');
  if (addedFiles.length > 0) {
    lines.push('# 3. Create new files');
    for (const add of addedFiles) {
      const target = strip(add.path);
      const body = contents?.get(add.path);
      if (body !== undefined && body.length > 0 && body.length <= MAX_INLINE_CONTENT) {
        lines.push(`cat > ${shellQuote(target)} <<'VRP_EOF'`);
        lines.push(body.replace(/\n$/, ''));
        lines.push('VRP_EOF');
      } else {
        lines.push(`touch ${shellQuote(target)}`);
      }
    }
    lines.push('');
  }

  if (deletes.length > 0) {
    lines.push('# 4. Remove deleted paths');
    for (const del of deletes) {
      const target = shellQuote(strip(del.path));
      lines.push(del.nodeType === 'folder' ? `rm -rf ${target}` : `rm -f ${target}`);
    }
    lines.push('');
  }

  lines.push('echo "Applied ' + topLevelChanges.length + ' change(s)."');
  return lines.join('\n');
}

export function generateAgentPrompt(diff: RepoDiff): string {
  const moves = diff.changes.filter((c) => c.type === 'move');
  const adds = diff.changes.filter((c) => c.type === 'add');
  const deletes = diff.changes.filter((c) => c.type === 'delete');

  if (moves.length === 0 && adds.length === 0 && deletes.length === 0) {
    return 'No repository layout changes have been made yet.';
  }

  const lines: string[] = [
    'I reorganized this repository\'s file layout. The files have already been',
    'moved on disk. Update every reference so the project still builds.',
    '',
    '### Path changes',
  ];

  if (moves.length > 0) {
    lines.push('', '**Moved or renamed:**');
    for (const move of moves) {
      lines.push(`- \`${strip(move.oldPath!)}\` → \`${strip(move.path)}\` (${move.nodeType})`);
    }
  }

  if (adds.length > 0) {
    lines.push('', '**Added:**');
    for (const add of adds) lines.push(`- \`${strip(add.path)}\` (${add.nodeType})`);
  }

  if (deletes.length > 0) {
    lines.push('', '**Removed:**');
    for (const del of deletes) lines.push(`- \`${strip(del.path)}\` (${del.nodeType})`);
  }

  lines.push(
    '',
    '### What to update',
    '1. Import and require statements pointing at any moved or removed path.',
    '2. Relative imports *inside* the moved files — their depth from the root changed.',
    '3. Path aliases and `paths` mappings in tsconfig/jsconfig, and bundler aliases.',
    '4. Non-code references: test globs, lint and build config, CI workflows, Dockerfiles,',
    '   and any dynamic `import()` or string path.',
    '5. Dead references left by removed files — delete them rather than stubbing them.',
    '',
    'Then run the build and the test suite, and report anything you could not resolve.',
  );

  return lines.join('\n');
}
